import {Platform, StyleSheet} from 'react-native';
import {Fonts, height, hp, width, wp} from 'theme';
import normalize from 'react-native-normalize';

export const componentsStyles = StyleSheet.create({
  searchContainer: {
    width: width / 1.1,
    backgroundColor: '#2E3D48',
    borderColor: '#B0E3F1',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
    borderRadius: 16,
    alignSelf: 'center',
    height: 42,
    marginTop: wp(12),
    right: 5,
    borderWidth: 1,
  },
  rateContainer: {
    flexDirection: 'row',
    top: 0,
    right: 15,
    paddingTop: 17,

    position: 'absolute',
  },
  filterRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#B0E3F1',
    borderRadius: 16,
    width: 81,
    height: 42,
    justifyContent: 'center',
  },
  ratingBox: {
    position: 'absolute',
    zIndex: 1,
    backgroundColor: 'white',
    width: width * 0.07,
    height: height * 0.015,
    right: width * 0.016,
    top: height * 0.014,
    borderRadius: 20,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
  },
  priceBox: {
    flexDirection: 'row',
    alignContent: 'flex-end',
    marginTop: height * 0.004,
    alignItems: 'center',
    marginHorizontal: width * 0.025,
    justifyContent: 'space-between',
    height: height * 0.05,
  },
  priceAmountTxt: {color: '#FF0F39', fontFamily: Fonts.CREG, fontSize: 15},
  priceCurrencyTxt: {
    fontFamily: Fonts.CREG,
    fontSize: 11,
    color: '#313131',
    marginLeft: width * 0.01,
  },
  bookDetailsWriterName: {
    textAlign: 'left',
    fontFamily: Fonts.CBOLD,
    fontSize: normalize(14),
    color: '#FF0F39',
  },
  bookDetailsBookName: {
    textAlign: 'left',
    fontFamily: Fonts.CREG,
    fontSize: normalize(22),
    color: 'black',
    lineHeight: 26,
  },
  bookDetailsDiscount: {
    fontFamily: Fonts.CREG,
    fontSize: 14,
    textAlign: 'left',
    alignSelf: 'flex-end',
    // marginRight: width * 0.03,
    color: '#D6D6D6',
    textDecorationLine: 'line-through',
    textDecorationStyle: 'solid',
  },
  bookDetailsPrice: {
    fontFamily: Fonts.CBOLD,
    fontSize: normalize(22),
    // marginRight: width * 0.01,
    color: '#FF0F39',
  },
  bookDetailsPriceCurrency: {
    fontFamily: Fonts.CREG,
    fontSize: normalize(12),
    // marginRight: width * 0.03,
    // lineHeight: normalize(45),
  },
  bookDetailsDesc: {
    fontFamily: Fonts.CREG,
    fontSize: normalize(12),
    lineHeight: normalize(27),
    textAlign: 'left',
    marginTop: height * 0.02,
    color: '#313131',
  },
  header: {
    height: Platform.OS === 'ios' ? height * 0.22 : height / 5,
    width: width,
    justifyContent: 'space-between',
    alignItems: 'center',
    flexDirection: 'row-reverse',
  },
  headerContainer: {
    flexDirection: 'row-reverse',
    justifyContent: 'space-between',
  },
  profileHeader: {
    height: height * 0.2,
    width: width,
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  profileHeaderEditIcon: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignSelf: 'flex-start',
    width: width,
    paddingHorizontal: wp(3),
    paddingVertical: hp(3),
  },
  profileHeaderImage: {
    flexDirection: 'row',
    justifyContent: 'center',
    width: width,
    top: normalize(35),
    zIndex: normalize(20),
  },
});
